### PR TITLE
Remove `typing.Literal` to make it work on Python 3.6

### LINKED ISSUE #140: ImportError: cannot import name 'Literal'
py-ard should support python 3.6

this construct `from typing import Iterable, Literal`  is only supported in python 3.8

### PR DESCRIPTION
**Pull request by pbashyal-nmdp**
Fixes #140

### CODE REVIEW

**Review by mmaiers-nmdp — COMMENTED** [review]
Its more than Literal, its also Iterable.
We can just require newer versions of python
